# Generated by Django 4.1.2 on 2022-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
