# Generated by Django 4.1.2 on 2022-10-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_isapproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='isApproved',
            new_name='approved',
        ),
    ]
