# Generated by Django 4.1.2 on 2022-10-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_remove_album_creation_datetime_album_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='created',
        ),
    ]
