# Generated by Django 4.1.2 on 2022-10-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_album_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='release_datetime',
            new_name='released',
        ),
    ]
