# Generated by Django 4.1.2 on 2022-10-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_rename_release_datetime_album_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='modified',
        ),
        migrations.AlterField(
            model_name='album',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
