# Generated by Django 4.1.2 on 2022-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
